"""The M7 milestone report, generated entirely from a run's `summary.json`.

Every sentence that makes a claim about a number computes it here from the summary. There
is no prose in this file that asserts a result: the adjectives ("dominates", "negligible",
"within tolerance") are all produced by comparisons against thresholds declared in
`configs/uncertainty.yaml`, so re-running the study rewrites the verdicts rather than
leaving them behind as stale text.

Sections that have no result yet print what is missing and why, and do not print a table
of blanks that could be mistaken for measurements.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from .comparison import COLUMN_UNITS, TPI_FOOTNOTE
from .inputs import TIER_LABEL


def _f(value: Any, fmt: str = ".4g") -> str:
    if value is None:
        return "—"
    try:
        x = float(value)
    except (TypeError, ValueError):
        return str(value)
    return "—" if not np.isfinite(x) else format(x, fmt)


def _pct(value: Any, digits: int = 1) -> str:
    if value is None:
        return "—"
    try:
        x = float(value)
    except (TypeError, ValueError):
        return str(value)
    return "—" if not np.isfinite(x) else f"{x * 100:.{digits}f}%"


def _table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


# ---------------------------------------------------------------------------------------

def _header(s: dict[str, Any]) -> str:
    fig = s.get("figures", [])
    return "\n".join([
        "# M7 — Uncertainty propagation and robust design",
        "",
        f"Run `{s['run_id']}` · git `{s['git_commit']}`"
        + (" **(dirty working tree)**" if s.get("git_dirty") else "")
        + f" · evaluator source hash `{s.get('source_hash', '?')}`",
        "",
        f"Aerodynamic model **{s.get('aero_model', '?')}** (Fidelity "
        f"{s.get('fidelity', '?')}) · "
        f"{s.get('n_evaluations', 0):,} coupled evaluations · "
        f"{s.get('wall_s', 0.0) / 60.0:.1f} min wall on {s.get('workers', '?')} workers",
        "",
        "> Generated by `scripts/run_uncertainty.py` / `scripts/run_robust_optimize.py` "
        "from this run's `summary.json`. Every number and every verdict below is computed "
        "from result files; nothing is hand-typed. Figures: "
        + (", ".join(f"`{Path(p).name}`" for p in fig) if fig else "none") + ".",
        "",
        *([f"> Hand-written companion for this run (paired same-draw differences, H0/H1 "
           f"restated under uncertainty, robust vs nominal, which uncertainty dominates): "
           f"`{s['addendum']}`. It is not generated; where it and this report disagree "
           "about a NUMBER, `summary.json` decides.", ""] if s.get("addendum") else []),
    ])


def _scope(s: dict[str, Any]) -> str:
    warnings = s.get("stale_warnings", [])
    lines = ["## 0. What this run is, and is not", ""]
    lines.append(
        "This is an uncertainty study of a **model**, not of a vehicle. It propagates the "
        "spread that `configs/uncertainty.yaml` declares, through the assumptions "
        "`ASSUMPTIONS.md` declares. It does not and cannot cover a model-form error that "
        "is not on that list — most importantly gate **G2′** (Sutton–Graves' catalycity, "
        "hot-wall and radiation assumptions, where catalycity alone is worth about a "
        "factor of two) is `LIMITED` and untouched here. An output distribution from this "
        "study is therefore a **lower bound on the real uncertainty**, and the §7 "
        "limitations section lists what is missing rather than leaving it implied.")
    lines.append("")
    if warnings:
        lines.append("```")
        lines += warnings
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def _inventory(s: dict[str, Any]) -> str:
    model = s["uncertainty_model"]
    lines = ["## 1. The uncertainty inventory", ""]
    lines.append(
        f"**{model['n_inputs']} active inputs**: {model['n_aleatory']} aleatory "
        f"(mission-to-mission variability) and {model['n_epistemic']} epistemic (model "
        f"form and unknown properties). By source tier: "
        + ", ".join(f"{TIER_LABEL[t]} × {n}" for t, n in model["tier_counts"].items() if n)
        + ".")
    lines.append("")
    rows = []
    for item in model["inputs"]:
        rows.append([
            f"`{item['name']}`",
            item["kind"],
            item["describe"],
            f"`{item['apply'].get('path', item['apply']['type'])}`",
            TIER_LABEL[item["tier"]],
        ])
    lines.append(_table(["Input", "Kind", "Distribution", "Applied to", "Tier"], rows))
    lines.append("")
    if model["skipped"]:
        lines.append("**Declared but not active in this run:**")
        lines.append("")
        lines.append(_table(["Input", "Why"],
                            [[f"`{r['name']}`", r["reason"]] for r in model["skipped"]]))
        lines.append("")
    lines.append(
        "Every input's full source line — including the verbatim sentences from NASA "
        "TN D-5121 and NASA TR R-376 that set the two largest terms — is in "
        "`configs/uncertainty.yaml`, which is snapshotted into this run's directory. An "
        "input tiered `T3` is engineering judgment and the loader refuses it unless its "
        "own source line says so.")
    lines.append("")
    profile = model.get("density_profile")
    if profile:
        lines.append("### 1.1 Atmospheric density dispersion vs altitude")
        lines.append("")
        rows = [[f"{z:g}", _pct(sig, 1), TIER_LABEL[t]]
                for z, sig, t in zip(profile["altitude_km"], profile["sigma_relative"],
                                     profile.get("tier", ["T3"] * len(profile["altitude_km"])),
                                     strict=False)]
        lines.append(_table(["Altitude [km]", "1 s.d. of density", "Tier"], rows))
        lines.append("")
        n_t1 = sum(1 for t in profile.get("tier", []) if t == "T1")
        lines.append(
            f"The {n_t1} rows below 86 km are standard deviations NASA published from its "
            "own GRAM validation against Shuttle re-entry data (NASA-TM-4715 Tables 3.1 "
            "and 3.3; NASA/TM-20210022157 pp. 63–65). The rows above it are **engineering "
            "judgment**: no document opened in the sourcing pass states a 1-σ density "
            "dispersion above 86 km, so those rows convert the primary *observed ranges* "
            "of the U.S. Standard Atmosphere Supplements 1966 falling-sphere data into a "
            "1-σ proxy. That conversion is this project's step. It matters more than it "
            "looks: NR-14 measured that 5–20% of a feasible design's heat load accrues in "
            "exactly that band.")
        lines.append("")
    return "\n".join(lines)


def _achieved_rows(s: dict[str, Any]) -> list[list[str]]:
    a = s.get("achieved_throughput") or {}
    if not a:
        return [["ACHIEVED throughput", "not recorded for this run"]]
    return [["**ACHIEVED throughput** (this run's paid evaluations / its wall clock)",
             f"**{_f(a['evaluations_per_second'], '.3g')} evaluations/s** "
             f"({a['n_evaluations']:,} evaluations in {_f(a['wall_s'], '.0f')} s)"],
            ["**ACHIEVED parallel efficiency** (achieved / ideal "
             f"{_f(a['ideal_evaluations_per_second'], '.3g')} evaluations/s)",
             f"**{_pct(a['parallel_efficiency'])}**"]]


def _sizing(s: dict[str, Any]) -> str:
    z = s.get("sizing", {})
    if not z:
        return ""
    lines = ["## 2. How the study was sized", ""]
    lines.append(_table(
        ["Quantity", "Value"],
        [["measured wall time per coupled evaluation",
          f"{_f(z.get('measured_seconds_per_evaluation'), '.4g')} s (single process, "
          "one BLAS thread)"],
         ["workers", str(z.get("workers"))],
         ["parallel efficiency ASSUMED for the projection (declared in the config)",
          _pct(z.get("assumed_parallel_efficiency", z.get("measured_parallel_efficiency")))],
         ["PROJECTED throughput = workers × assumed efficiency / seconds per evaluation",
          _f(z.get("projected_evaluations_per_second",
                   z.get("measured_evaluations_per_second")), ".3g")
          + " evaluations/s (a projection, not a measurement)"],
         *_achieved_rows(s),
         ["propagation", f"{z.get('propagation_evaluations', 0):,} evaluations "
                         f"(~{_f(z.get('propagation_seconds'), '.3g')} s)"],
         ["attribution", f"{z.get('attribution_evaluations', 0):,} evaluations "
                         f"(~{_f(z.get('attribution_seconds'), '.3g')} s)"],
         ["robust optimisation", f"{z.get('robust_evaluations', 0):,} evaluations "
                                 f"(~{_f(z.get('robust_seconds'), '.3g')} s)"],
         ["shortcut verification", f"{z.get('verification_evaluations', 0):,} evaluations "
                                   f"(~{_f(z.get('verification_seconds'), '.3g')} s)"],
         ["§39 comparison", f"{z.get('comparison_evaluations', 0):,} evaluations "
                            f"(~{_f(z.get('comparison_seconds'), '.3g')} s)"],
         ["**total projected**", f"**{z.get('total_evaluations', 0):,} evaluations, "
                                 f"~{_f(z.get('total_seconds', 0.0) / 60.0, '.3g')} min**"],
         ["budget", f"{_f(z.get('budget_seconds', 0.0) / 60.0, '.3g')} min"]]))
    lines.append("")
    lines.append(
        "The per-evaluation time is measured at launch and the two ACHIEVED rows are "
        "measured after the run; the assumed efficiency, the projected throughput and "
        "every per-stage and total time are projections made before the first evaluation. "
        "Until 2026-09-21 this table printed the projected rate and the "
        "declared efficiency under the words \"measured\" and \"achieved\" (NR-34 item 1); "
        "older `summary.json` files still store them under `measured_*` keys.")
    lines.append("")
    robust = s.get("robust") or {}
    if robust and not z.get("robust_evaluations"):
        paid = sum(r["budget_used"] for r in robust.get("runs", []))
        ver = robust.get("verification") or {}
        lines.append(
            f"The zeros against robust optimisation and shortcut verification are THIS "
            f"run's own share: that work was done by run `{robust.get('run_id', '?')}` "
            f"({paid:,} inner evaluations paid by the search"
            + (f", {ver['n_designs']} × {ver['n_full']:,} by the verification"
               if ver.get("n_designs") else "")
            + f"; {_f(robust.get('wall_s', 0.0) / 60.0, '.0f')} min wall on "
            f"{robust.get('workers', '?')} workers) and is folded in here from its files.")
        lines.append("")
    fits = z.get("fits_budget")
    if fits is not None:
        lines.append(f"The projected total **{'fits' if fits else 'DOES NOT fit'}** the "
                     f"{_f(z.get('budget_seconds', 0.0) / 3600.0, '.2g')} hour budget "
                     "declared in `configs/uncertainty.yaml`.")
        lines.append("")
    return "\n".join(lines)


def _propagation(s: dict[str, Any]) -> str:
    blocks = s.get("propagation", {})
    if not blocks:
        return "## 3. Propagation\n\nNot run in this run.\n"
    draws = s["draws"]
    lines = ["## 3. Propagation (spec §27)", ""]
    lines.append(
        f"Sampling mode **{draws['mode']}**: {draws['n_epistemic_branches']} epistemic "
        f"branches × {draws['n_aleatory']} aleatory draws sharing common random numbers "
        f"= {draws['n_samples']} evaluations per design, seed {draws['seed']}. "
        "Every sample is a full coupled evaluation through `evaluate_design`.")
    lines.append("")

    lines.append("### 3.1 Output statistics")
    lines.append("")
    for i, name in enumerate(s["objectives"], start=1):
        lines.append(f"#### 3.1.{i} {name}")
        lines.append("")
        rows = []
        for label, block in blocks.items():
            c = block["combined"].get(name, {})
            d = block["decomposition"].get(name, {})
            band = block["band"].get(name, {}).get("p95", {})
            rows.append([
                f"`{label}`",
                _f(block.get("nominal", {}).get(name)),
                _f(c.get("mean")), _f(c.get("std")),
                _f(c.get("percentiles", {}).get("p5")),
                _f(c.get("percentiles", {}).get("p95")),
                _f(c.get("percentiles", {}).get("p99")),
                _f(d.get("std_aleatory")), _f(d.get("std_epistemic")),
                f"[{_f(band.get('min'))}, {_f(band.get('max'))}]",
            ])
        lines.append(_table(
            ["Design", "nominal", "mean", "s.d.", "p5", "p95", "p99",
             "s.d. aleatory", "s.d. epistemic", "p95 band over branches"], rows))
        lines.append("")
        shares = {label: blocks[label]["decomposition"].get(name, {})
                  .get("epistemic_share_of_variance") for label in blocks}
        usable = {k: v for k, v in shares.items() if v is not None and np.isfinite(v)}
        if usable:
            lo, hi = min(usable.values()), max(usable.values())
            verdict = ("**epistemic ignorance dominates**" if lo > 0.5 else
                       "**aleatory variability dominates**" if hi < 0.5 else
                       "**neither source dominates across all designs**")
            lines.append(
                f"Epistemic share of the variance runs from {_pct(lo)} to {_pct(hi)} "
                f"across the designs studied, so for this output {verdict}. "
                + ("Ignorance of this kind is removable by evidence, not by design "
                   "margin — §5 says which measurement would remove the most of it."
                   if lo > 0.5 else
                   "Variability of this kind is not removable by further study; it has "
                   "to be absorbed by margin, which is what §6's robust formulation "
                   "does."))
            lines.append("")
    lines.append(
        "The `mean` and `s.d.` columns describe the **pooled mixture** of variability and "
        "ignorance. That pooling combines the two in quadrature (the law of total "
        "variance), which is exact for the sampled mixture but is only *meaningful* if an "
        "epistemic band — \"one of these two NASA reports is right and we do not know "
        "which\" — is read as a probability distribution. It is not one. The **p95 band "
        "over branches** column is the view that does not require that reading, and it is "
        "the one a design decision should be taken on.")
    lines.append("")
    return "\n".join(lines)


def _violations(s: dict[str, Any]) -> str:
    blocks = s.get("propagation", {})
    if not blocks:
        return ""
    lines = ["### 3.2 Constraint-violation probability", "",
             "Every probability below carries a Wilson score interval, and a count of "
             "zero is reported as an upper bound rather than as zero. A draw whose "
             "trajectory produced no physics at all counts as a violation and is also "
             "reported separately.", ""]
    names = sorted({n for b in blocks.values() for n in b["violations"]})
    rows = []
    for label, block in blocks.items():
        for name in names:
            v = block["violations"].get(name)
            if v is None:
                continue
            rows.append([f"`{label}`", name, f"{v['n_violations']} / {v['n_samples']}",
                         str(v["n_not_evaluable"]), v["phrase"]])
    lines.append(_table(["Design", "Constraint", "count", "no physics", "P(violation)"],
                        rows))
    lines.append("")
    nominal_feasible_but_risky = []
    for label, block in blocks.items():
        v = block["violations"].get("any")
        nom_ok = block.get("nominal_feasible")
        if v and nom_ok and v["point"] > 0.05:
            nominal_feasible_but_risky.append((label, v["point"]))
    if nominal_feasible_but_risky:
        listed = ", ".join(f"`{lbl}` at {_pct(p)}" for lbl, p in nominal_feasible_but_risky)
        lines.append(
            f"**Fragility found.** {listed} — these designs are feasible at their nominal "
            "point and violate at least one constraint on more than one draw in twenty "
            "once the declared uncertainty is switched on. Spec §28 forbids choosing a "
            "nominally excellent but fragile design without discussion; §6 is that "
            "discussion.")
        lines.append("")
    return "\n".join(lines)


def _between_branch_share(blocks: dict[str, Any]) -> str:
    """How much of the convergence output's variance is between branches - from §3.1's
    decomposition, not asserted."""
    shares = []
    for block in blocks.values():
        output = block["convergence"]["output"]
        share = block.get("decomposition", {}).get(output, {}).get(
            "epistemic_share_of_variance")
        if share is not None and np.isfinite(share):
            shares.append(float(share))
    if not shares:
        return "the between-branch share of this output's variance was not recorded."
    return (f"{_pct(min(shares))}–{_pct(max(shares))} of this output's variance is between "
            "branches (§3.1 decomposition).")


def _convergence(s: dict[str, Any]) -> str:
    blocks = {k: b for k, b in s.get("propagation", {}).items()
              if b.get("convergence", {}).get("table")}
    if not blocks:
        return ""
    draws = s.get("draws", {})
    lines = ["### 3.3 Convergence of the statistics", ""]
    rows, strict_rows = [], []
    for label, block in blocks.items():
        conv = block["convergence"]
        cluster = (conv.get("cluster_bootstrap") or {}).get("statistics", {})
        for stat, verdict in conv["verdict"].items():
            c = cluster.get(stat, {})
            rows.append([f"`{label}`", stat, f"{verdict.get('n', '—')}",
                         _f(verdict.get("value")),
                         _pct(verdict.get("half_width_rel"), 2),
                         _pct(verdict.get("tolerance_rel"), 2),
                         "yes" if verdict.get("converged") else "**no**",
                         _pct(c.get("half_width_rel"), 2) if c else "—",
                         ("—" if not c else
                          "yes" if c.get("within_tolerance") else "**no**")])
            if c:
                strict_rows.append((label, stat, c, verdict))
    lines.append(_table(["Design", "Statistic", "N", "value",
                         "ROW bootstrap half-width (the pre-declared check)",
                         "declared tolerance", "pre-declared check met?",
                         "BRANCH (cluster) bootstrap half-width (post hoc)",
                         "declared tolerance met on the branch bootstrap?"], rows))
    lines.append("")
    failed = [r for r in rows if r[6] != "yes"]
    lines.append(
        "**The pre-declared check is the ROW bootstrap**, as `configs/uncertainty.yaml` "
        "declared it before the run, and its verdict is the only verdict here: "
        + ("all reported statistics are within the declared tolerance on it."
           if not failed else
           f"**{len(failed)} of {len(rows)} reported statistics are NOT within the declared "
           "tolerance at the sample size used.** Those numbers are quoted with their "
           "intervals throughout and must not be read to more precision than the interval "
           "supports; the study was sized to a wall-clock budget, and this is what that "
           "cost."))
    lines.append("")
    if strict_rows:
        info = next(iter(blocks.values()))["convergence"]["cluster_bootstrap"]
        ratios = [c["half_width_rel"] / v["half_width_rel"] for _, _, c, v in strict_rows
                  if v.get("half_width_rel")]
        missed = [(label, stat, c) for label, stat, c, _ in strict_rows
                  if not c["within_tolerance"]]
        unit = s["units"].get(next(iter(blocks.values()))["convergence"]["output"], "")
        lines.append(
            f"**That check understates the sampling error, and the second pair of columns "
            f"is why (NR-34 item 2).** The draw set is {draws.get('mode', '?')}: "
            f"{draws.get('n_epistemic_branches', '?')} epistemic branches × "
            f"{draws.get('n_aleatory', '?')} shared aleatory draws, so the "
            f"{draws.get('n_samples', '?')} rows are not independent - every row of a branch "
            "shares one value of every epistemic input, and "
            + _between_branch_share(blocks)
            + " A bootstrap must resample the unit that "
            f"was independently drawn. Resampling whole branches ({info['n_clusters']} "
            f"clusters, {info['n_bootstrap']} resamples, seed {info['seed']}) gives "
            f"half-widths {min(ratios):.0f}–{max(ratios):.0f} times the row bootstrap's. "
            "This second bootstrap was added after the run; it is reported beside the "
            "pre-declared check, never instead of it, and it changes no verdict.")
        lines.append("")
        if missed:
            lines.append(
                "Applying the declared tolerance to the branch bootstrap - the stricter "
                "reading, not the declared one - "
                + "; ".join(f"the `{label}` {stat} misses it ({_pct(c['half_width_rel'], 2)} "
                            f"= ±{_f(c['half_width'], '.2g')} {unit}"
                            f" against {_pct(c['tolerance_rel'], 2)})"
                            for label, stat, c in missed)
                + f"; the other {len(strict_rows) - len(missed)} of {len(strict_rows)} "
                "statistics meet it. So \"converged to a few hundredths of a percent\" is "
                "not a fair summary of this table: absolute means and percentiles here are "
                "known to roughly the branch-bootstrap half-width. More epistemic branches, "
                "not more draws, is what would tighten them.")
        else:
            lines.append("On the branch bootstrap every statistic still meets the declared "
                         "tolerance.")
        lines.append("")
    return "\n".join(lines)


def _attribution(s: dict[str, Any]) -> str:
    blocks = s.get("attribution", {})
    if not blocks:
        return ""
    lines = ["## 4. What drives the spread (spec §27)", "",
             "Sobol' first- and total-order indices over the uncertain inputs, computed "
             "with M4's estimator on the **mean-centred** output — an uncentred "
             "first-order estimator on an output with a 400 K mean produced confidence "
             "intervals wider than [0, 1] the first time this repository tried it "
             "(NR-16).", ""]
    for n_block, (label, block) in enumerate(blocks.items(), start=1):
        lines.append(f"### 4.{n_block} Design `{label}`  "
                     f"({block['n_evaluations']:,} evaluations, n_base "
                     f"{block['n_base']})")
        lines.append("")
        for output, data in block.get("outputs", {}).items():
            names = [i["name"] for i in block["inputs"]]
            kinds = [i["kind"] for i in block["inputs"]]
            total = np.asarray(data["total"], dtype=float)
            first = np.asarray(data["first"], dtype=float)
            ci = np.asarray(data["total_ci"], dtype=float)
            order = np.argsort(-total)
            rows = [[names[i], kinds[i], _f(first[i], ".3f"), _f(total[i], ".3f"),
                     f"[{_f(ci[i, 0], '.3f')}, {_f(ci[i, 1], '.3f')}]"]
                    for i in order]
            lines.append(f"**{output}**")
            lines.append("")
            lines.append(_table(["Input", "Kind", "S_i", "S_T", "95% CI on S_T"], rows))
            lines.append("")
            top = names[order[0]]
            top_kind = kinds[order[0]]
            lines.append(
                f"The largest total-order index is `{top}` at {_f(total[order[0]], '.3f')}"
                + (f", an **{top_kind}** input — so the single most effective way to "
                   "narrow this output is to resolve that piece of evidence, not to add "
                   "design margin." if top_kind == "epistemic" else
                   f", an **{top_kind}** input — no amount of further study narrows it, "
                   "so it has to be absorbed by margin.") + "\n")
        k = block.get("k_body_over_nose")
        if k is not None and np.isfinite(k) and k >= 0.999:
            lines.append(
                f"On this design K = R_b/R_n = {_f(k, '.3f')}, i.e. the forebody is a "
                "**hemisphere**. There the two primaries agree identically by Zoby & "
                "Sullivan's own eq. (5) — R_eff = R_b = R_n whichever table is used — so "
                "`effective_nose_radius_model` can move nothing at all and its index of "
                "zero is a property of this geometry, not a broken input. The M4 front "
                "sits at K ≈ 0.42, where the two sources disagree by about 20%, and that "
                "is where this term is expected to dominate.\n")
        for output, why in block.get("not_computed", {}).items():
            lines.append(f"**{output}: NOT COMPUTED.** {why}\n")
    return "\n".join(lines)


def _robust(s: dict[str, Any]) -> str:
    block = s.get("robust")
    if not block:
        return ("## 5. Robust optimisation (spec §28)\n\n"
                "Not run in this run. `make robust` produces it.\n")
    st = block["settings"]
    lines = ["## 5. Robust optimisation (spec §28)", "",
             "### 5.1 The problem, declared before the run", ""]
    lines.append(_table(
        ["Setting", "Value"],
        [["robust objectives", f"{st['objective_percentile']:g}th percentile of "
                               + " and ".join(f"`{o}`" for o in s["objectives"])],
         ["quantile estimator", f"`{st['quantile_estimator']}`"],
         ["chance constraints", ", ".join(f"P({k}) ≤ {_pct(v, 0)}"
                                          for k, v in st["chance_constraints"].items())],
         ["inner sample per candidate", f"{st['inner_samples']} draws, "
                                        "common random numbers"],
         ["population / budget / seeds",
          f"{st['population_size']} / {st['budget_evaluations']:,} per seed / "
          f"{st['seeds']}"]]))
    lines.append("")
    runs = block.get("runs", [])
    if runs:
        lines.append(_table(
            ["Seed", "generations", "evaluations paid", "cache hits", "front size",
             "stopped because"],
            [[str(r["seed"]), str(r["generations"]), f"{r['budget_used']:,}",
              f"{r['cache_hits']:,}", str(r.get("front_size", "—")),
              r["stopped_because"]] for r in runs]))
        lines.append("")
        hits = sum(r["cache_hits"] for r in runs)
        paid = sum(r["budget_used"] for r in runs)
        if paid:
            lines.append(
                "Common random numbers mean a design the optimiser re-proposes is re-tested "
                "on exactly the same draws and served from cache at no cost. Measured in "
                f"this run: **{hits:,} cache hits in {hits + paid:,} inner evaluations "
                f"({_pct(hits / (hits + paid))})**. "
                + ("The optimiser never re-proposed a design, so that saving did not "
                   "occur; what common random numbers did do is compare every candidate on "
                   "the same inner draws."
                   if hits == 0 else
                   "That saving is logged per candidate rather than assumed."))
            lines.append("")

    lines.append("### 5.2 Verifying the shortcut")
    lines.append("")
    ver = block.get("verification")
    if not ver:
        lines.append("**Not performed in this run.** The robust front must therefore be "
                     "read as the output of an unverified shortcut.")
        lines.append("")
    else:
        lines.append(
            f"{ver['n_designs']} designs drawn evenly along the finished robust front "
            f"were re-scored with **full, independent Monte Carlo**: {ver['n_full']} "
            f"fresh draws at seed {ver['full_seed']}, no common random numbers, against "
            f"the {ver['n_inner']}-draw CRN shortcut the optimiser used.")
        lines.append("")
        rows = [[name, str(d["n_compared"]), _pct(d["mean_relative_bias"], 2),
                 _pct(d["max_abs_relative_error"], 2),
                 _f(d["spearman_rank_correlation"], ".3f"),
                 _pct(d["mean_abs_error_over_full_span"], 2)]
                for name, d in ver["objectives"].items()]
        lines.append(_table(["Robust objective", "n", "mean relative bias",
                             "max abs rel. error", "Spearman ρ",
                             "mean abs error / front span"], rows))
        lines.append("")
        rows = [[name, _pct(d["alpha"], 0), _pct(d["max_abs_difference"], 2),
                 _pct(d["mean_abs_difference"], 2), str(d["n_verdict_disagreements"])]
                for name, d in ver["probabilities"].items()]
        lines.append(_table(["Chance constraint", "α", "max |Δp|", "mean |Δp|",
                             "feasibility verdicts that flipped"], rows))
        lines.append("")
        lines.append(("**Verdict: PASSED.** " if ver["verdict"]["passed"]
                      else "**Verdict: FAILED.** ") + ver["verdict"]["statement"] + ".")
        if ver["verdict"]["failures"]:
            lines.append("")
            lines += [f"  - {f}" for f in ver["verdict"]["failures"]]
        lines.append("")

    lines.append("### 5.3 Nominal versus robust")
    lines.append("")
    moved = [e for e in s.get("nominal_designs_under_uncertainty", [])
             if e.get("is_nominal_optimum")]
    if moved:
        rows = []
        for entry in moved:
            rows.append([
                f"`{entry['label']}`",
                _f(entry["nominal"].get(s["objectives"][1])),
                _f(entry["p95"].get(s["objectives"][1])),
                _f(entry.get("nominal_margin_pct")),
                entry.get("violation_phrase", "—"),
            ])
        lines.append(_table(
            ["Nominal-optimal design", f"nominal {s['objectives'][1]}",
             f"95th percentile {s['objectives'][1]}",
             "nominal margin [%]", "P(any constraint violated)"], rows))
        lines.append("")
        worst = max(moved, key=lambda e: e.get("violation_point", 0.0))
        lines.append(
            f"The nominal-optimal designs sit between "
            f"{_f(min(e.get('nominal_margin_pct', np.inf) for e in moved), '.2g')}% and "
            f"{_f(max(e.get('nominal_margin_pct', -np.inf) for e in moved), '.2g')}% from "
            "their own binding constraint at the nominal point. Once the declared "
            f"uncertainty is switched on, the most exposed of them, `{worst['label']}`, "
            f"violates a constraint on {worst.get('violation_phrase', '—')}. "
            "This is the §28 discussion: a design is not chosen here on nominal "
            "excellence alone.")
        lines.append("")
    cost = s.get("cost_of_robustness")
    if cost:
        lines.append(_table(
            ["Comparison", "Value"],
            [[k.replace("_", " "), _f(v)] for k, v in cost.items()]))
        lines.append("")
    return "\n".join(lines)


def _cell_phrase(s: dict[str, Any], cell: dict[str, Any]) -> str:
    parts = [f"n = {cell.get('n_samples', '?')}"]
    parts += [f"{name} p95 {_f(cell.get(name, {}).get('p95'))}" for name in s["objectives"]]
    anyv = cell.get("violation_probability", {}).get("any", {})
    if anyv:
        parts.append(f"P(violation) {anyv.get('phrase', '—')}")
    return "; ".join(parts)


def _likeforlike_notes(s: dict[str, Any], table: dict[str, Any],
                       replaced: list[tuple[str, dict[str, Any]]]) -> list[str]:
    """Are the uncertainty cells of the §39 rows the same kind of sample? Said either way."""
    draws = s.get("draws", {})
    prov = table.get("provenance", {})
    lfl = s.get("robust_likeforlike") or {}
    sizes = {r["label"]: r.get("uncertainty", {}).get("n_samples") for r in table["rows"]
             if r.get("available")}
    lines: list[str] = []
    if not lfl:
        if len(set(sizes.values())) > 1:
            lines += [
                "**The uncertainty cells are NOT like-for-like.** Rows that already had a "
                f"propagation reuse it ({draws.get('n_samples')} {draws.get('mode')} draws, "
                f"seed {draws.get('seed')}); a row without one gets "
                f"{prov.get('uncertainty_samples')} mixed draws on seed "
                f"{prov.get('uncertainty_seed')}. Those rows cannot be paired draw for draw "
                "with the others. `scripts/run_m7_robust_likeforlike.py` closes the gap.", ""]
        return lines
    eq = lfl["evaluator_equivalence"]
    lines.append(
        f"**Like-for-like.** All four uncertainty cells above are now the same sample: "
        f"{draws.get('n_samples')} {draws.get('mode')} draws "
        f"({draws.get('n_epistemic_branches')} epistemic branches × {draws.get('n_aleatory')} "
        f"aleatory), seed {draws.get('seed')}. The `{lfl['comparison_row']}` cell comes from "
        f"a separate, labelled run, `{lfl['run_id']}`: a propagation of that ONE design "
        f"through this run's draw set ({lfl['n_evaluations']:,} evaluations, "
        f"{_f(lfl['wall_s'] / 60.0, '.1f')} min), made after the study; it is not a re-run of "
        "the study and no other number in this report comes from it. It ran under evaluator "
        f"source hash `{lfl['source_hash']}` (this study: `{lfl['parent_source_hash']}`) "
        "because report and plotting code under `src/aether` was edited in between; before "
        f"propagating, it re-ran {eq['n_evaluations']} of this study's own `{eq['design']}` "
        "evaluations and reproduced the logged outputs to a largest relative difference of "
        f"{max(eq['max_relative_difference'].values()):.1e} (required ≤ "
        f"{eq['rtol_required']:.0e}; feasibility identical: "
        f"{'yes' if eq['feasibility_identical'] else 'NO'}).")
    lines.append("")
    for label, cell in replaced:
        lines.append(
            f"As this study originally generated it, the `{label}` cell was: "
            f"{_cell_phrase(s, cell)} - {prov.get('uncertainty_samples')} *mixed* draws on "
            f"seed {prov.get('uncertainty_seed')}, a different draw set from the other rows. "
            "It is kept here and in the addendum; it is superseded in the table only "
            "because it could not be compared or paired with them.")
        lines.append("")
    conv = (lfl.get("convergence") or {}).get("cluster_bootstrap", {}).get("statistics", {})
    if conv:
        lines.append(
            "Sampling error of the like-for-like cell "
            f"({(lfl.get('convergence') or {}).get('output')}, branch bootstrap, see §3.3): "
            + "; ".join(f"{stat} ±{_pct(c['half_width_rel'], 2)}" for stat, c in conv.items())
            + ".")
        lines.append("")
    pairs = lfl.get("paired") or []
    if pairs:
        lines.append(f"**Paired on the shared draws** (`{lfl['label']}` minus the named "
                     "design, same draw; interval = bootstrap over whole epistemic branches):")
        lines.append("")
        lines.append(_table(
            ["Difference", "Output", "mean", "s.d.", "p5 … p95", "min … max",
             "draws with Δ < 0", "95% CI on the mean"],
            [[f"`{p['a']}` − `{p['b']}`", f"`{p['output']}`", _f(p["mean"], "+.4g"),
              _f(p["sd"], ".3g"),
              f"{_f(p['percentiles']['p5'], '+.4g')} … {_f(p['percentiles']['p95'], '+.4g')}",
              f"{_f(p['min'], '+.4g')} … {_f(p['max'], '+.4g')}",
              f"{p['n_draws_a_below_b']} / {p['n_pairs']}",
              f"[{_f(p['mean_ci95_cluster_bootstrap'][0], '+.4g')}, "
              f"{_f(p['mean_ci95_cluster_bootstrap'][1], '+.4g')}]"] for p in pairs]))
        lines.append("")
        lines.append("A difference that keeps one sign in every draw holds within the "
                     "declared uncertainty model only; a model error common to both designs "
                     "(gate G2′ above all) moves them together and a paired test cannot see "
                     "it.")
        lines.append("")
    return lines


def _comparison(s: dict[str, Any]) -> str:
    table = s.get("comparison")
    if not table:
        return ("## 6. Final comparison (spec §39)\n\nNot generated in this run.\n")
    lines = ["## 6. Final comparison (spec §39)", ""]
    lines.append(
        "Four designs, every one **re-evaluated under this run's source hash** so that "
        "they are comparable with each other. Where a design came from an earlier run, "
        "the value that run stored is quoted underneath with the difference, because a "
        "design optimised under a different heating model is a fact about this project's "
        "history and overwriting it would erase that.")
    lines.append("")
    columns = list(table["columns"])
    header = ["Metric", "Units", *[r["label"] for r in table["rows"]]]
    rows = []
    for name in columns:
        cells = []
        for row in table["rows"]:
            if not row["available"]:
                cells.append("NOT AVAILABLE")
                continue
            value = _f(row["metrics"].get(name))
            if name in row["stored_metrics"]:
                stored = _f(row["stored_metrics"][name])
                delta = row["deltas"].get(name)
                cells.append(f"{value}<br><sub>stored {stored}, Δ {_f(delta, '+.3g')}</sub>")
            else:
                cells.append(value)
        rows.append([f"`{name}`", COLUMN_UNITS.get(name, ""), *cells])
    rows.append(["**feasible**", "",
                 *[("—" if not r["available"] else
                    ("yes" if r["feasible"] else "**no**")) for r in table["rows"]]])
    lfl = s.get("robust_likeforlike") or {}
    replaced: list[tuple[str, dict[str, Any]]] = []
    unc = []
    for row in table["rows"]:
        cell = row.get("uncertainty", {})
        if lfl and row.get("available") and row["label"] == lfl.get("comparison_row"):
            replaced.append((row["label"], cell))
            cell = lfl["uncertainty_cell"]
        if not row["available"] or not cell.get("available"):
            unc.append(cell.get("reason", "—") if not cell.get("available") else "—")
            continue
        # the sample size is per ROW, not per table: a design that already had a full
        # propagation reuses it rather than paying for a second, smaller one
        parts = [f"n = {cell.get('n_samples', '?')}"]
        for name in s["objectives"]:
            block = cell.get(name, {})
            parts.append(f"{name}: p95 {_f(block.get('p95'))}")
        anyv = cell.get("violation_probability", {}).get("any", {})
        if anyv:
            parts.append(f"P(violation) {anyv.get('phrase', '—')}")
        unc.append("<br>".join(parts))
    rows.append(["**uncertainty**", "per row", *unc])
    lines.append(_table(header, rows))
    lines.append("")
    lines += _likeforlike_notes(s, table, replaced)
    lines.append(f"> **On the penetration metric.** {TPI_FOOTNOTE}")
    lines.append("")
    for warning in table.get("stale_warnings", []):
        lines.append("```")
        lines.append(warning)
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def _largest_index_among(s: dict[str, Any], names: list[str]) -> str:
    """Where, in §4, the named inputs carry the most variance - from the indices."""
    best: tuple[float, str, str, str] | None = None
    for label, block in (s.get("attribution") or {}).items():
        inputs = [i["name"] for i in block.get("inputs", [])]
        for output, data in block.get("outputs", {}).items():
            for name, value in zip(inputs, data["total"], strict=False):
                if name in names and np.isfinite(value) and (best is None or value > best[0]):
                    best = (float(value), name, label, output)
    if best is None:
        return ""
    return (f" The largest total-order index any of them reaches in §4 is "
            f"{_f(best[0], '.3f')} (`{best[1]}`, design `{best[2]}`, `{best[3]}`).")


def _limitations(s: dict[str, Any]) -> str:
    model = s["uncertainty_model"]
    t3 = [i["name"] for i in model["inputs"] if i["tier"] == "T3"]
    skipped = [r["name"] for r in model["skipped"]]
    lines = ["## 7. Limitations", ""]
    t1 = [i["name"] for i in model["inputs"] if i["tier"] == "T1"]
    lines.append(
        f"**{len(t3)} of {model['n_inputs']} active inputs are engineering judgment** "
        f"(`{'`, `'.join(t3)}`). Their spreads are declared, not sourced, and the width of "
        "every output distribution here is conditional on them. "
        + (f"{len(t1)} input{'s are' if len(t1) != 1 else ' is'} tiered "
           f"{TIER_LABEL['T1']} (`{'`, `'.join(t1)}`)." if t1 else
           f"No input is tiered {TIER_LABEL['T1']}.")
        + _largest_index_among(s, t1))
    lines.append("")
    aero_terms = [i for i in model["inputs"]
                  if str(i["apply"].get("path", "")).startswith("vehicle.aero.")]
    if int(s.get("fidelity", 0)) == 0:
        if skipped:
            lines.append(
                f"**Not propagated in this run:** `{'`, `'.join(skipped)}`. This run is "
                f"Fidelity 0 (`{s.get('aero_model')}`): the sourced C_D terms of the "
                "CFD-surface branch (GP predictive σ with its stored inflation, the M2 "
                "discretisation band, the base-drag band and the declared perfect-gas "
                "half-band) do not exist here"
                + (f", and C_D uncertainty is carried by "
                   f"`{'`, `'.join(i['name'] for i in aero_terms)}` instead"
                   if aero_terms else "")
                + ". That substitution is not equivalent and the C_D-related numbers here "
                "should not be carried into a Fidelity-1 discussion.")
            lines.append("")
    else:
        lines.append(
            f"**Drag uncertainty.** This run is Fidelity {s.get('fidelity')} "
            f"(`{s.get('aero_model')}`), and {len(aero_terms)} C_D term"
            f"{'s were' if len(aero_terms) != 1 else ' was'} propagated: "
            + ", ".join(f"`{i['name']}` ({TIER_LABEL[i['tier']]})" for i in aero_terms)
            + "."
            + ("".join(f" Declared but not active: `{r['name']}` - {r['reason']}."
                       for r in model["skipped"]) if model["skipped"] else ""))
        lines.append("")
    lines.append(
        "**Not covered at all.** Gate G2′ (aeroheating model form: catalycity, hot wall, "
        "radiation) is `LIMITED` and is not in the inventory; catalycity alone is "
        "reported at roughly a factor of two. A-TPS-2's temperature-independent "
        "conductivity, A-TPS-3's adiabatic back face, A-HEAT-4's stagnation-point-only "
        "treatment and A-TRAJ-1's non-rotating Earth are structural model-form choices "
        "with no distribution attached. The deceleration limit itself is an **open "
        "student decision** (A-LIM-1b): 12 g corresponds to no documented sustained-g "
        "curve, and adopting the NASA-STD-3001 deconditioned curve would empty the "
        "feasible region. Every chance constraint on `max_g` below is therefore a "
        "statement about a placeholder limit.")
    lines.append("")
    lines.append(
        "**The atmosphere above 86 km.** Gate G1A′ is `PASS` for five transcribed rows "
        "and `LIMITED` for everything else, the interpolation between rows is not the "
        "species-diffusion model USSA-76 actually defines there, and NR-14 measured that "
        "5–20% of a feasible design's heat load comes from that band. Two inputs here — "
        "the >86 km density dispersion rows and the high-altitude heating multiplier — "
        "are engineering judgment about exactly that region, so the study quantifies the "
        "consequence of a known weakness without removing it.")
    lines.append("")
    return "\n".join(lines)


def _reproduce(s: dict[str, Any]) -> str:
    return "\n".join([
        "## 8. Reproducing this",
        "",
        "```bash",
        "make uncertainty          # propagation, attribution, §39 table",
        "make robust               # robust optimisation + shortcut verification",
        f"make uncertainty-report RUN_ID={s['run_id']}   # every figure + this report, "
        "no evaluation",
        f"# this run: {s['run_id']}, source hash {s.get('source_hash', '?')}",
        "```",
        "",
        "Every seed is in `configs/uncertainty.yaml` and is snapshotted with the run. "
        "The study is deterministic given the seeds and the evaluator source: the runner "
        "records the source-tree hash at launch and **aborts** if `src/aether` changes "
        "while it is running, because worker processes would otherwise hold two different "
        "physics models within one candidate log (NR-18).",
        "",
        f"Results: `results/M7/{s['run_id']}/` — `candidates.csv` (every evaluation), "
        "`draws.csv` (every uncertainty draw), `summary.json` (every number this report "
        "quotes), `comparison.csv` (the §39 table in long form), "
        "`config_snapshot.yaml`.",
        "",
    ])


def write_m7_report(root: Path, summary: dict[str, Any], path: Path | None = None) -> Path:
    """Render the milestone report and write it. Returns the path written."""
    published = path is None
    path = path or (Path(root) / "reports" / "milestones" / "M7_uncertainty_robust.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    companion = path.parent / "M7_addendum_posthoc.md"
    summary = {**summary, "addendum": companion.name
               if published and companion.exists()
               and str(summary.get("run_id")) in companion.read_text() else None}
    sections = [_header(summary), _scope(summary), _inventory(summary), _sizing(summary),
                _propagation(summary), _violations(summary), _convergence(summary),
                _attribution(summary), _robust(summary), _comparison(summary),
                _limitations(summary), _reproduce(summary)]
    path.write_text("\n".join(s for s in sections if s).rstrip() + "\n")
    return path


def write_summary(out_dir: Path, summary: dict[str, Any]) -> Path:
    path = Path(out_dir) / "summary.json"
    path.write_text(json.dumps(summary, indent=2, default=float))
    return path
