"""Generate reports/milestones/M3_coupled_model.md FROM result files.

No number in the report is typed here: every value is read from the design-point tables, the
surface summary, the coupled-study tables, or M2's own gate file. Prose explains; files decide.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from ..aerodynamics.cfd_surface import discretisation_band, gate_g4_status
from ..utils.run import REPO_ROOT

REPORT = REPO_ROOT / "reports" / "milestones" / "M3_coupled_model.md"


def _pct(x: float, digits: int = 2) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{100.0 * x:+.{digits}f}%"


def _md(frame: pd.DataFrame, fmt: dict[str, str] | None = None) -> str:
    fmt = fmt or {}
    cols = list(frame.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in frame.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            if isinstance(v, (float, np.floating)):
                cells.append("" if not np.isfinite(v) else format(v, fmt.get(c, ".4g")))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _read(path: Path) -> pd.DataFrame:
    try:
        return pd.read_csv(path) if path.exists() else pd.DataFrame()
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def write_report(dp_dir: Path, level: str, cfg: dict[str, Any], dp_cfg: dict[str, Any]) -> Path:
    run_id = dp_dir.name
    table = _read(dp_dir / f"design_points_{level}.csv")
    attempts = _read(dp_dir / f"attempts_{level}.csv")
    skipped = _read(dp_dir / "design_skipped.csv")
    ssum = json.loads((dp_dir / f"surface_summary_{level}.json").read_text())
    dsum_path = dp_dir / f"summary_{level}.json"
    dsum = json.loads(dsum_path.read_text()) if dsum_path.exists() else {}
    inv_path = dp_dir / f"invocations_{level}.jsonl"
    inv = [json.loads(line)["driver_wall_time_s"] for line in inv_path.read_text().splitlines()
           if line.strip()] if inv_path.exists() else []
    mesh = _read(dp_dir / f"mesh_check_{level}.csv")
    finer_attempts = _read(dp_dir / f"attempts_{cfg['surface']['mesh_check_level']}.csv")
    mach_ind = _read(dp_dir / f"mach_independence_{level}.csv")
    base = _read(dp_dir / f"base_drag_fraction_{level}.csv")
    csum = json.loads((dp_dir / "coupled" / "summary.json").read_text())
    gate5 = json.loads((dp_dir / "coupled" / "gate_G5.json").read_text())
    bands = _read(dp_dir / "coupled" / "mach_bands_constant_cd.csv")
    g4 = gate_g4_status()
    disc = discretisation_band(level)

    pts = table[table["role"] != "scale_check"]
    usable = pts[pts["verdict"] == "USABLE"]
    bad = pts[pts["verdict"] != "USABLE"]
    out: list[str] = []
    w = out.append

    w("# M3 - Coupled geometry / CFD / trajectory / TPS model: the CFD-derived drag surface")
    w("")
    w(f"*Generated by `scripts/run_m3_coupled.py` from `results/M3/{run_id}/`. "
      "Every number below is read from a result file.*")
    w("")
    w("> **PROVISIONAL.** `gate_G4_status_at_build: IN_PROGRESS`. When this surface was built "
      "the M2 fine-mesh sphere cases had not finished, so validation gate G4 was not PASS. "
      f"At the time this report was generated, `{g4['source']}` says G4 is "
      f"**{g4['status']}**. Until G4 is PASS the surface may not feed any optimisation "
      "(spec §17): `cfd_surface_v1` is registered but **off** - no config selects it, "
      "`configs/design_space.yaml` still says `aero.model: constant`, and the builder refuses "
      "to serve the surface unless a config sets `allow_provisional: true`, which only the "
      "G5 study and its tests do.")
    w("")
    w(f"> **Mesh level: {level.upper()}, not the medium mesh the brief asked for.** "
      "Reason and evidence in §2. Discretisation uncertainty is taken from the M2 GCI through "
      "a hook that reads `results/M2/<run>/gci.csv` "
      f"(`aerodynamics.cfd_surface.discretisation_band`); right now that hook returns "
      f"`available = {disc['available']}`"
      + (f", band = {100 * disc['rel_band']:.3f}% from `{disc['source']}`."
         if disc["available"] else " because M2 has no three-level GCI yet. No number has been "
         "typed in its place."))
    w("")

    # -- 1 -------------------------------------------------------------------------------
    w("## 1. What the model is")
    w("")
    w("```\nC_D(M, shape) = C_D,fore(M, shape)   Gaussian process through converged CFD cases "
      "(inviscid, perfect gas, alpha = 0)\n              + C_D,base(M)          stated "
      "assumption with a band - NOT computed (A-CFD-5)\n```")
    w("")
    w("Inputs: log(Mach) and three forebody ratios - bluntness R_n/D, cone half-angle, shoulder "
      "ratio R_c/D. The forebody-only CFD domain (A-CFD-4) ends at the maximum-radius station, "
      "so the aft cone angle and the length cannot influence C_D,fore and are not inputs. "
      "**Angle of attack is zero by construction** (axisymmetric wedge mesh): no lift, no "
      "moments, no stability - a model limit, acceptable only because the entry studied is "
      "ballistic (spec §18: C_L only if required). The trajectory consumes a per-capsule "
      "1-D interpolant of the surface; it never calls CFD or the GP inside a time step.")
    w("")

    # -- 2 -------------------------------------------------------------------------------
    w("## 2. Design points")
    w("")
    n_anchor = int((pts["role"] == "anchor").sum())
    n_fill = int((pts["role"] == "fill").sum())
    w(f"- Planned: **{len(pts)}** design points = {n_anchor} hull anchors (run at both ends of "
      f"the Mach range) + {n_fill} scrambled-Sobol fill points (seed "
      f"{dp_cfg['design']['seed']}), of which {dp_cfg['design']['holdout']['n_test']} were "
      "marked as the held-out test set before any case ran; plus 2 scale-check cases.")
    late = dp_cfg["design"].get("late_anchors", [])
    if late:
        w(f"- {2 * len(late)} of those anchor cases ({len(late)} shapes) are **late anchors, "
          "added after the first pass**: the hull did not enclose the M4 front (NR-22). They "
          "were chosen from the front's shape range, not from any CFD value.")
    w(f"- **{len(skipped)}** candidate shapes were skipped as geometrically invalid, each with "
      f"its reason, in `results/M3/{run_id}/design_skipped.csv`.")
    inp = dp_cfg["inputs"]
    w(f"- Ranges: Mach {inp['mach']['min']:g}-{inp['mach']['max']:g} (log-spaced), bluntness "
      f"{inp['bluntness_ratio']['min']}-{inp['bluntness_ratio']['max']}, cone half-angle "
      f"{inp['cone_half_angle_deg']['min']:g}-{inp['cone_half_angle_deg']['max']:g} deg, "
      f"shoulder ratio {inp['shoulder_ratio']['min']}-{inp['shoulder_ratio']['max']} "
      "(the M4 design-space box).")
    if len(attempts):
        okat = attempts[attempts["status"] == "OK"]
        w(f"- Wall time ({level} mesh, {dsum.get('max_concurrent_cases', 4)} serial cases side by "
          f"side): median **{okat['solver_wall_time_s'].median():.0f} s** per completed case "
          f"(min {okat['solver_wall_time_s'].min():.0f}, max "
          f"{okat['solver_wall_time_s'].max():.0f}); sum over all "
          f"{len(attempts)} attempts {attempts['total_wall_time_s'].sum() / 3600.0:.2f} "
          "core-hours." + (f" Driver wall time, summed over {len(inv)} invocation(s) of the "
                           f"resumable driver: {sum(inv) / 3600.0:.2f} h." if inv else ""))
    if len(finer_attempts):
        okf = finer_attempts[finer_attempts["status"] == "OK"]
        if len(okf):
            w(f"- The same pipeline on the **{cfg['surface']['mesh_check_level']}** mesh: median "
              f"**{okf['solver_wall_time_s'].median():.0f} s** per completed case "
              f"({len(okf)} cases) - the measured reason the full design was not run there.")
    w("")
    w("**Why coarse.** The brief asked for the M2 medium mesh. Measured on this machine "
      "(fanless 4-performance-core laptop, M2 benchmark still running, interactive use), a "
      "medium case costs roughly eight times a coarse one (4x the cells, 2x the iterations), "
      "which put the full design at 7-8 hours against a ~2 hour budget. Running ~15 medium "
      "points instead would not support a 4-input surface. So every point was run on the "
      "coarse mesh, and a seeded subset was re-run on the medium mesh to MEASURE the "
      "coarse-to-medium change on capsule shapes (§5). `make cfd-design-points LEVEL=medium "
      f"RUN_ID={run_id}` produces the all-medium table (resumable).")
    w("")
    w("![design coverage](../figures/M3_design_coverage.png)")
    w("")

    # -- 3 -------------------------------------------------------------------------------
    w("## 3. What converged, what did not, and why")
    w("")
    counts = pts["verdict"].value_counts()
    w(_md(pd.DataFrame({"verdict": counts.index, "cases": counts.to_numpy()})))
    w("")
    w("A case is USABLE only if it ran, met the **unchanged M2 force-convergence criterion**, "
      "left the outflow plane supersonic everywhere (A-CFD-4), and kept the bow shock clear of "
      "the inflow boundary - checked on the axis (stand-off vs distance to the boundary) and "
      "off it (outermost outflow faces still at freestream Mach). Nothing else is used to fit "
      "the surface. Every failed or rejected case stays on disk and is listed here:")
    w("")
    if len(bad):
        cols = ["point_id", "role", "mach", "bluntness_ratio", "cone_half_angle_deg",
                "shoulder_ratio", "verdict", "attempts", "reasons"]
        w(_md(bad[cols].fillna(""), {"mach": ".2f", "bluntness_ratio": ".3f",
                                     "cone_half_angle_deg": ".1f", "shoulder_ratio": ".3f"}))
    else:
        w("*(none)*")
    w("")
    if len(attempts):
        is_patience = (attempts["patience_pass"] == True) if "patience_pass" in attempts \
            else pd.Series(False, index=attempts.index)  # noqa: E712
        retried = attempts[(attempts["attempt"] > 0) & ~is_patience]
        w(f"Domain re-runs: **{len(retried)}** extra attempts over "
          f"{retried['case'].str.rsplit('_a', n=1).str[0].nunique() if len(retried) else 0} "
          "design points (a crash or a failed shock-clearance check triggers a re-run in an "
          f"enlarged domain; every attempt is a row of `attempts_{level}.csv`).")
        if "patience_pass" in attempts:
            pat = attempts[attempts["patience_pass"] == True]  # noqa: E712
            if len(pat):
                rescued = pat[pat["verdict"] == "USABLE"]["case"].str.split("_").str[0]
                w(f"Patience pass: **{len(pat)}** cases missed the force criterion after M2's 3 "
                  "extensions in the first pass and were given one more attempt with up to "
                  f"{dp_cfg['acceptance']['convergence_retry']['max_extensions']} - the "
                  "criterion itself unchanged (NR-09's rule). "
                  f"**{len(rescued)}** then met it"
                  + (f" ({', '.join(sorted(rescued))})" if len(rescued) else "")
                  + f"; {len(pat) - len(rescued)} still did not and stay REJECTED. This rule was "
                  "added after the first pass had been seen, which the config says.")
        if len(usable):
            w(f"Among USABLE cases: minimum outflow Mach "
              f"{usable['outlet_min_mach'].min():.3f}; smallest axis clearance fraction "
              f"{usable['upstream_clearance_fraction'].min():.3f}; extensions needed: "
              f"{usable['n_extensions'].value_counts().sort_index().to_dict()}.")
    w("")

    # -- 4 -------------------------------------------------------------------------------
    w("## 4. Two checks the surface leans on")
    w("")
    sc = dsum.get("scale_check", {})
    if sc.get("performed"):
        w(f"**Scale invariance.** Inviscid perfect-gas flow has no length scale, so C_D should "
          f"not depend on diameter. Checked, not assumed: the same shape at Mach "
          f"{dp_cfg['scale_check']['mach']:g} at D = {sc['diameters_m'][0]:g} m and "
          f"{sc['diameters_m'][1]:g} m gives C_D,fore = {sc['cd_fore'][0]:.5f} and "
          f"{sc['cd_fore'][1]:.5f}, a relative difference of "
          f"{100 * sc['rel_difference']:.4f}% (declared tolerance "
          f"{100 * sc['tolerance']:.2f}%): "
          f"{'scale-invariant' if sc['scale_invariant'] else '**NOT within tolerance**'}. "
          "All design points were therefore run at one diameter.")
    else:
        w("**Scale invariance.** The two-diameter check has not completed in this run; the "
          "claim that C_D is independent of diameter is therefore an ARGUMENT (the Euler "
          "equations of a perfect gas contain no length scale), not yet a measurement here.")
    w("")
    if len(usable):
        err = usable["p_stag_rel_error_vs_rayleigh_pitot"]
        w(f"**Stagnation pressure against the exact Rayleigh-pitot relation**, on every usable "
          f"case (a check that holds at ANY Mach number, including above the M2 benchmark's "
          f"Mach 6): median error {100 * err.median():+.3f}%, worst {100 * err.abs().max():.3f}% "
          f"({usable.loc[err.abs().idxmax(), 'point_id']}).")
    w("")

    # -- 5 -------------------------------------------------------------------------------
    w("## 5. Discretisation: coarse vs medium on capsule shapes")
    w("")
    if len(mesh):
        w(_md(mesh[["point_id", "mach", "bluntness_ratio", "cone_half_angle_deg",
                    "cd_fore_coarse", "cd_fore_finer", "rel_change"]].assign(
            rel_change=lambda d: 100 * d["rel_change"]).rename(
            columns={"rel_change": "change [%]"}),
            {"cd_fore_coarse": ".5f", "cd_fore_finer": ".5f", "change [%]": "+.3f",
             "mach": ".2f", "bluntness_ratio": ".3f", "cone_half_angle_deg": ".1f"}))
        w("")
        finer_tab = _read(dp_dir / f"design_points_{cfg['surface']['mesh_check_level']}.csv")
        if len(finer_tab):
            fbad = finer_tab[finer_tab["verdict"] != "USABLE"]
            w(f"{len(finer_tab)} points were re-run on the medium mesh (seeded subset + the "
              f"M4-front and baseline shapes at Mach 20); {len(fbad)} of them "
              + (f"({', '.join(fbad['point_id'])}) " if len(fbad) else "")
              + "did not meet the force criterion there and are not paired. The medium runs "
              "did not get the patience pass.")
            w("")
        w(f"Largest coarse-to-medium change in C_D,fore over {len(mesh)} paired capsule cases: "
          f"**{100 * mesh['rel_change'].abs().max():.3f}%**. This is a two-level difference, "
          "not a GCI: it shows the size of the effect, it does not bound the error.")
    else:
        w("No design point has yet been run on both meshes; the medium-mesh subset is "
          f"`make cfd-design-points LEVEL=medium SUBSET=mesh-check RUN_ID={run_id}`.")
    w("")

    # -- 6 -------------------------------------------------------------------------------
    w("## 6. Response surface (spec §25)")
    w("")
    w(f"Gaussian process (`aether.surrogate.GPSurrogate`: Matern-5/2, one length scale per "
      f"input, white-noise term) on **{ssum['n_usable']}** usable CFD points. Surface hash "
      f"`{ssum['training_hash']}`; persisted as the training table plus pinned kernel "
      "hyper-parameters in `data/aero/cfd_surface_v1/`, so a reload is bit-for-bit.")
    w("")
    rows = []
    ho = ssum["holdout"]
    if "inside_hull" in ho:
        for name, blk in (("held-out test, inside hull", ho["inside_hull"]),
                          ("held-out test, all", ho["all"])):
            if blk.get("n"):
                rows.append({"set": name, **_flat(blk)})
    for name, key in (("k-fold, inside fold hull", "inside_hull"), ("k-fold, all", "all"),
                      ("k-fold, outside fold hull", "outside_hull")):
        blk = ssum["k_fold"][key]
        if blk.get("n"):
            rows.append({"set": name, **_flat(blk)})
    if rows:
        w(_md(pd.DataFrame(rows), {"rmse": ".4f", "mae": ".4f", "r2": ".4f", "z_std": ".2f",
                                   "cov50": ".2f", "cov68": ".2f", "cov90": ".2f",
                                   "cov95": ".2f"}))
    w("")
    w(f"Held-out test set: {ho['n_test_planned']} planned, {ho['n_test_usable']} usable "
      f"(the others failed the acceptance rules in §3). k = {ssum['k_fold']['k']} folds. "
      f"RMSE/MAE are in C_D units; C_D,fore spans {ssum['cd_fore_range'][0]:.3f}-"
      f"{ssum['cd_fore_range'][1]:.3f}. `cov68` is the fraction of truths inside the "
      "predicted central 68% interval (nominal 0.68); `z_std` > 1 means overconfident. "
      "With this few points the coverage figures are themselves uncertain by roughly "
      "±1/sqrt(n).")
    w("")
    w(f"**Calibration.** Where the k-fold z-score spread exceeds 1 the GP is overconfident. "
      f"The measured spread over all usable points is used as a **sigma inflation factor of "
      f"{ssum['sigma_inflation']:.2f}**, stored with the surface and applied to the GP term "
      "before M7 samples it. This is a one-number recalibration, not a fix: the held-out "
      "points above show a bias as well as a spread, and n is small.")
    w("")
    w("**Extrapolation guard.** A capsule whose shape lies outside the convex hull of the "
      "usable CFD points is refused: `evaluate_design` returns it as a rejected candidate "
      "(`status: aero surface extrapolation: ...`, NaN metrics) that stays in the candidate "
      "log. `on_extrapolation: flag` overrides and labels the result. Failed CFD cases "
      "therefore shrink the usable design space - see §3 for where.")
    w("")
    w("![cv](../figures/M3_surface_cv.png)")
    w("")
    w("![cd vs mach](../figures/M3_cd_vs_mach.png)")
    w("")

    # -- 7 -------------------------------------------------------------------------------
    w("## 7. Mach range: where the entry actually happens")
    w("")
    if len(bands):
        b0 = bands[bands["design"] == bands["design"].iloc[0]]
        w(f"Baseline capsule, constant C_D: entry Mach {b0['mach_at_entry'].iloc[0]:.1f}, "
          f"maximum {b0['mach_max'].iloc[0]:.1f}, Mach at peak heating "
          f"**{b0['mach_at_peak_heating'].iloc[0]:.1f}**, at peak deceleration "
          f"**{b0['mach_at_peak_g'].iloc[0]:.1f}**.")
        w("")
        w(_md(b0[["mach_lo", "mach_hi", "heat_load_fraction", "time_s"]].assign(
            heat_load_fraction=lambda d: 100 * d["heat_load_fraction"]).rename(
            columns={"heat_load_fraction": "heat load [%]", "time_s": "flight time [s]"}),
            {"heat load [%]": ".2f", "flight time [s]": ".1f", "mach_lo": ".0f",
             "mach_hi": ".0f"}))
        w("")
    w("So a surface over the M2 benchmark's Mach 3-6 alone would cover almost none of the "
      "heating. The design therefore runs to Mach 20 - and the perfect-gas solver can, because "
      "its equations contain only Mach number and gamma. What that does and does not mean:")
    w("")
    w("- **Above Mach 20 the value at Mach 20 is held.** The basis is Mach-number independence "
      "of blunt-body pressure drag (Anderson, *Hypersonic and High-Temperature Gas Dynamics*, "
      "2nd ed., AIAA 2006, ch. 4 'Hypersonic Inviscid Flowfields: Approximate Methods', "
      "§4.3 'Mach-Number Independence' - chapter and section titles verified against the "
      "Library of Congress table of contents, catdir.loc.gov/catdir/toc/ecip0618/"
      "2006025724.html; **the book's text itself was not opened for this project**, so the "
      "principle is cited, not quoted). It is also measured on this surface:")
    w("")
    if len(bands):
        top = bands[(bands["design"] == bands["design"].iloc[0])
                    & (bands["mach_lo"] >= inp["mach"]["max"])]["heat_load_fraction"].sum()
        w(f"  **This matters: {100 * top:.0f}% of the baseline capsule's heat load is "
          f"accumulated above Mach {inp['mach']['max']:g}**, i.e. on the held value. The "
          "surface is only as good there as Mach-number independence is.")
        w("")
    if len(mach_ind):
        inside_mi = mach_ind[(~mach_ind["extrapolated"]) & (mach_ind["mach_lo"] == 10.0)]
        if len(inside_mi):
            w(f"  Largest change in C_D,fore between Mach 10 and 20 among the named shapes "
              f"inside the hull: {100 * inside_mi['rel_change'].abs().max():.2f}%. Not zero: "
              "holding the Mach-20 value above Mach 20 is an approximation of about that size, "
              "not an identity.")
            w("")
        w(_md(mach_ind.assign(rel_change=lambda d: 100 * d["rel_change"]).rename(
            columns={"rel_change": "change [%]"}),
            {"cd_fore_lo": ".4f", "cd_fore_hi": ".4f", "change [%]": "+.3f",
             "mach_lo": ".0f", "mach_hi": ".0f"}))
        w("")
    w("- **The perfect gas is wrong for the shock layer at these speeds** (no dissociation, "
      "far too hot, shock too far out - `docs/validation/M2_model_form_limits.md`). It is "
      "adequate *to first order for pressure drag only*: surface pressure is set by the normal "
      "momentum flux, and the stagnation Cp moves only from about 1.84 (gamma = 1.4) to the "
      f"Newtonian 2.0. That argument is **not validated here**; it is carried as a declared "
      f"half-band of ±{100 * ssum['model_form_rel_halfband_declared']:.0f}% on C_D,fore for M7 "
      "to sample, and it biases in a known direction (real-gas C_D slightly HIGHER).")
    w("- **Below Mach 3 the value at Mach 3 is held.** Not physics: transonic and subsonic "
      "capsule drag is base-dominated and outside this model's permitted use. It is tolerable "
      "because of how little of the entry happens there - quantified in §10.")
    w("- M2 validated the solver at Mach 3 and 6 only. Between Mach 6 and 20 the only "
      "per-case check is the exact stagnation pressure (§4).")
    w("")

    # -- 8 -------------------------------------------------------------------------------
    w("## 8. Base drag (closes A-CFD-5 as an assumption, not as a result)")
    w("")
    w("`C_D,base = (1 - p_b/p_inf) * 2/(gamma M^2) * (A_base/A_ref)` - algebra. All the "
      "uncertainty is in the base-pressure ratio, which is **bounded, not predicted**: from 0 "
      "(exact vacuum limit) up to 1 for Mach <= 6 and up to 3 for Mach >= 10. The upper value "
      "comes from NASA TN D-4800 (Miller 1968) figure 11(b), opened and read for this "
      "milestone: area-mean p_b/p_inf for blunted 9-degree cones at Mach 10-20 lies between "
      "about 0.2 and about 3, rising with Mach and bluntness (read off a log-scale graph by "
      "eye, ±30%). The same report states base drag was under about 2% of total for bluntness "
      "0.55-0.8. Nominal p_b/p_inf is 0.5 (Mach <= 6) rising to 1.0 (Mach >= 10): declared "
      "choices inside the band. A_base/A_ref = 1 (largest possible). No source found gives a "
      "flight-Reynolds-number value (sourcing report, unresolved gap).")
    w("")
    if len(base):
        show = base[["shape", "mach", "cd_fore", "cd_base_low", "cd_base_nominal",
                     "cd_base_high", "base_fraction_low", "base_fraction_nominal",
                     "base_fraction_high"]].copy()
        for c in ("base_fraction_low", "base_fraction_nominal", "base_fraction_high"):
            show[c] = 100 * show[c]
        show = show.rename(columns={"base_fraction_low": "frac low [%]",
                                    "base_fraction_nominal": "frac nominal [%]",
                                    "base_fraction_high": "frac high [%]"})
        w(_md(show, {"mach": ".0f", "cd_fore": ".4f", "cd_base_low": "+.4f",
                     "cd_base_nominal": "+.4f", "cd_base_high": "+.4f",
                     "frac low [%]": "+.2f", "frac nominal [%]": "+.2f",
                     "frac high [%]": "+.2f"}))
        w("")
        hi = base[base["mach"] >= 10.0]
        lo = base[base["mach"] <= 3.0]
        if len(hi) and len(lo):
            w(f"Across the named shapes the nominal base share of total C_D is "
              f"{100 * lo['base_fraction_nominal'].min():.1f}-"
              f"{100 * lo['base_fraction_nominal'].max():.1f}% at Mach 3 and "
              f"{100 * hi['base_fraction_nominal'].abs().max():.2f}% or less in magnitude at "
              f"Mach >= 10, where the band spans "
              f"{100 * hi['base_fraction_low'].min():+.2f}% to "
              f"{100 * hi['base_fraction_high'].max():+.2f}%. A negative share means base "
              "pressure above freestream (a small thrust).")
    w("")
    w("![base drag](../figures/M3_base_drag_fraction.png)")
    w("")

    # -- 9 -------------------------------------------------------------------------------
    w("## 9. Uncertainty exposed to M7")
    w("")
    w("```\nC_D = C_D,fore * (1 + z_disc*s_disc + u_form*h_form) + z_gp*s_gp(M) + "
      "C_D,base(M; u_base)\n```")
    w("")
    w("| term | draw | size | status |\n|---|---|---|---|")
    w("| GP predictive | z_gp ~ N(0,1), one per trajectory | s_gp(M) from the GP "
      "(max over report shapes in the figure) | measured (§6) |")
    w("| discretisation | z_disc ~ N(0,1) | s_disc = band/2, band from the M2 GCI hook | "
      + (f"band = {100 * disc['rel_band']:.3f}% read from `{disc['source']}`"
         if disc["available"] else
         "**NOT AVAILABLE until G4** - requesting z_disc != 0 raises, never a silent zero")
      + " |")
    w(f"| model form (perfect gas) | u_form ~ U(-1,1) | h_form = "
      f"{100 * ssum['model_form_rel_halfband_declared']:.0f}% | declared, NOT validated |")
    w("| base pressure | u_base ~ U(-1,1) | band of §8 | sourced band, declared nominal |")
    w("")
    w("Set through `vehicle.aero.uncertainty: {z_gp, z_discretisation, u_model_form, u_base}`; "
      "all default to zero (the nominal surface). Transferring a sphere's GCI to a capsule is "
      "itself an assumption (A-CFD-9).")
    w("")

    # -- 10 ------------------------------------------------------------------------------
    w("## 10. Gate G5 and the coupled comparison")
    w("")
    w(f"**G5 status: {gate5['status']}** - {gate5['status_reason']}.")
    w("")
    w(_md(pd.DataFrame({"check": list(gate5["checks"]),
                        "met": [str(v) for v in gate5["checks"].values()]})))
    w("")
    w(f"`evaluate_design` was run {gate5['repeats']} times on the same config with the surface "
      f"on; result fingerprints (every metric, margin, diagnostic, the provenance block and "
      f"the velocity history, bit for bit): `{'`, `'.join(gate5['fingerprints'])}`.")
    w("")
    w("### Constant C_D vs CFD surface, same design")
    w("")
    moves = pd.DataFrame(csum["constant_vs_surface"])
    if len(moves):
        show = pd.DataFrame({
            "design": moves["design"],
            "C_D const": moves["cd_constant"],
            "C_D surface @ peak q": moves["cd_surface_at_peak_heating"],
            "peak flux [%]": 100 * moves["peak_heat_flux_rel_change"],
            "bondline [K]": moves["peak_bondline_change_k"],
            "max g [%]": 100 * moves["max_g_rel_change"],
            "heat load [%]": 100 * moves["heat_load_rel_change"],
            "feasible const→surf": moves["feasible_constant"].astype(str) + "→"
            + moves["feasible_surface"].astype(str),
            "outside hull": moves["shape_extrapolated"].astype(str),
        })
        w(_md(show, {"C_D const": ".3f", "C_D surface @ peak q": ".4f",
                     "peak flux [%]": "+.2f", "bondline [K]": "+.2f", "max g [%]": "+.2f",
                     "heat load [%]": "+.2f"}))
        w("")
        w(f"Heat-load share flown outside the CFD Mach range (surface arm): below Mach "
          f"{inp['mach']['min']:g}: {100 * moves['heat_fraction_below_cfd_mach'].max():.2f}% at "
          f"most; above Mach {inp['mach']['max']:g}: "
          f"{100 * moves['heat_fraction_above_cfd_mach'].min():.1f}-"
          f"{100 * moves['heat_fraction_above_cfd_mach'].max():.1f}% (value held, §7).")
    w("")
    inc = ssum.get("inclusive_sensitivity_surface")
    if inc and len(moves) and "inclusive_cd_at_peak_heating" in moves:
        w("")
        w(f"**Sensitivity to the strict convergence rule.** {inc['n_extra']} cases "
          f"(`{'`, `'.join(inc['extra_point_ids'])}`) passed every acceptance rule except force "
          f"convergence and stayed inside a {100 * inc['max_peak_to_peak_rel_allowed']:.0f}% "
          "band. They are NOT in `cfd_surface_v1`. A second, labelled INCLUSIVE surface that "
          "also takes them was fitted only to see how much the strict rule costs in the "
          "corner of the shape space it removes:")
        w("")
        show = pd.DataFrame({
            "design": moves["design"],
            "outside hull strict→inclusive": moves["shape_extrapolated"].astype(str) + "→"
            + moves["inclusive_shape_extrapolated"].astype(str),
            "C_D @ peak q strict": moves["cd_surface_at_peak_heating"],
            "C_D @ peak q inclusive": moves["inclusive_cd_at_peak_heating"],
            "peak flux [%] strict": 100 * moves["peak_heat_flux_rel_change"],
            "peak flux [%] inclusive": 100 * moves["inclusive_peak_heat_flux_rel_change"],
            "bondline [K] strict": moves["peak_bondline_change_k"],
            "bondline [K] inclusive": moves["inclusive_peak_bondline_change_k"],
        })
        w(_md(show, {c: "+.2f" if "[" in c else ".4f" for c in show.columns}))
    w("")
    w("![constant vs surface](../figures/M3_constant_vs_surface.png)")
    w("")
    w("### Does capsule shape matter now?")
    w("")
    se = csum["shape_effect"]
    if se.get("n_shapes_in_hull", 0):
        w(f"At constant C_D the forebody shape had **no aerodynamic consequence at all**. With "
          f"the surface, over {se['n_shapes_in_hull']} swept shapes inside the CFD hull "
          f"(of {se['n_shapes_swept']} swept; same diameter, mass and entry state), C_D at peak "
          f"heating ranges **{se['cd_at_peak_heating_min']:.3f}-"
          f"{se['cd_at_peak_heating_max']:.3f}**. Acting through drag alone (each shape "
          f"compared with ITS OWN constant-C_D evaluation, so the heating model's shape "
          f"dependence cancels), that moves peak heat flux by "
          f"{_pct(se['peak_flux_change_via_drag_min'])} to "
          f"{_pct(se['peak_flux_change_via_drag_max'])}, peak bondline temperature by "
          f"{se['bondline_change_via_drag_min_k']:+.1f} to "
          f"{se['bondline_change_via_drag_max_k']:+.1f} K, and peak deceleration by "
          f"{_pct(se['max_g_change_via_drag_min'])} to {_pct(se['max_g_change_via_drag_max'])}. "
          "The model predicts that shape now matters; how much of that survives G4, the "
          "medium mesh and a re-run of the DOE is for M4 to establish.")
    else:
        w("No swept shape lay inside the CFD hull; see `coupled/shape_sweep.csv`.")
    w("")
    w("![shape sweep](../figures/M3_shape_sweep.png)")
    w("")
    w("### How much do the objectives care about what the surface cannot know?")
    w("")
    sens = pd.DataFrame(csum["sensitivity_baseline_capsule"])
    if len(sens):
        w(_md(sens.assign(peak_heat_flux_rel_change=lambda d: 100 * d[
            "peak_heat_flux_rel_change"], max_g_rel_change=lambda d: 100 * d[
            "max_g_rel_change"]).rename(columns={
                "peak_heat_flux_rel_change": "peak flux [%]",
                "peak_bondline_change_k": "bondline [K]", "max_g_rel_change": "max g [%]"}),
            {"peak flux [%]": "+.3f", "bondline [K]": "+.3f", "max g [%]": "+.3f"}))
        w("")
        w("`low_mach_x0.7 / x1.3` scale the HELD value below the lowest CFD Mach by ∓30%: that "
          "is the quantified form of the claim that the low-supersonic and subsonic tail does "
          "not matter to the thermal objectives. Baseline capsule, surface arm.")
    w("")

    # -- 11 ------------------------------------------------------------------------------
    w("## 11. Limits (what this surface is not)")
    w("")
    w("- Inviscid, calorically perfect gas, zero angle of attack, steady, forebody only. Not a "
      "flight C_D. Permitted and forbidden uses: `docs/validation/M2_model_form_limits.md`. "
      "**No heating quantity comes from this CFD.**")
    w(f"- Provisional until G4 is PASS; {level} mesh; discretisation band pending the M2 GCI.")
    w("- Base drag is an assumption with a band, not a computation.")
    w("- Held constant outside Mach 3-20.")
    w("- A few dozen CFD points in four inputs: the GP's error bars are the honest summary of "
      "what it knows, and its coverage statistics rest on a small sample.")
    w("- Failed CFD cases remove their corner of the shape space from the usable hull (§3).")
    w("")
    w("## 12. Reproduce")
    w("")
    w("```\nmake cfd-design-points                      # hours; OpenFOAM; resumable with "
      "RUN_ID=\nmake cfd-design-points LEVEL=medium SUBSET=mesh-check RUN_ID=<run>\n"
      "make aero-surface RUN_ID=<run>              # seconds\nmake m3-coupled   RUN_ID=<run>"
      "              # ~1 min; writes this report\n```")
    w("")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(out))
    return REPORT


def _flat(block: dict[str, Any]) -> dict[str, Any]:
    cov = block.get("coverage", {})
    return {"n": block["n"], "rmse": block["rmse"], "mae": block["mae"], "r2": block["r2"],
            "z_std": block.get("z_std", float("nan")),
            "cov50": cov.get("0.50", float("nan")), "cov68": cov.get("0.68", float("nan")),
            "cov90": cov.get("0.90", float("nan")), "cov95": cov.get("0.95", float("nan"))}
